<?php echo $this->doctype() . PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<?php echo $this->headMeta() . PHP_EOL; ?>
    <meta name="viewport" content="width=300, user-scalable=no">
	<?php
		$this->loadSkin($this->skin);
		echo $this->headLink() . PHP_EOL;
	?>
	<?php echo $this->headScript() . PHP_EOL; ?>
</head>
<body>
	<div id="wrapper">
		<?php echo $this->layout()->content; ?>
	</div>
</body>
</html>